apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-service-ing
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins-jenkins-k8s
          servicePort: 80
